name: media-stack
services:

  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:v3.39.1
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - FREE_ONLY=${FREE_ONLY}
    networks:
      - mynetwork
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
    healthcheck:
      test: ["CMD", "pgrep", "openvpn"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: "unless-stopped"

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.0.0
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    restart: "no"  # Will not restart automatically if VPN is unhealthy

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.13.1
    networks:
      mynetwork:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.10
    container_name: sonarr
    networks:
      mynetwork:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.25.4
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - prowlarr-config:/config
    restart: "no"  # Will not restart automatically if VPN is unhealthy

  jellyseerr:
    image: fallenbagel/jellyseerr:2.0.1
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.9.11
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  cleanmyarr-config:

networks:
  mynetwork:
    external: true